#!/bin/sh /etc/rc.common

START=21
STOP=9
USE_PROCD=1

start_service() {
	echo 1 4 1 7 > /proc/sys/kernel/printk
	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param command /usr/bin/gl-e750-mcu.lua
	procd_close_instance
}

stop_service() {
	echo 7 4 1 7 > /proc/sys/kernel/printk
}